#!/bin/bash

source /etc/os-release
MIRROR="https://mirror.xenyth.net/fedora/linux/releases"
VERSION_NEXT=$(($VERSION_ID + 1))

check () {
	curl -s -o /dev/null $MIRROR

	if [[ $? != 0 ]]; then
		echo "Internet connection, or mirror, is offline. Trying again in 60 seconds.."
		sleep 60
		check
		return
	fi

	local mirror_response=$(curl -s -o /dev/null -w "%{http_code}" $MIRROR/$VERSION_NEXT/)

	case $mirror_response in
			404)
				echo "Fedora $VERSION_ID is the latest version."
				;;
			200)
				upgrade
				;;
			*)
				echo "Mirror returned unhandled HTTP Response Code: $mirror_response."
				;;
	esac
}

upgrade () {
	dnf upgrade --refresh -y
	dnf system-upgrade download --releasever=$VERSION_NEXT -y

	wall "WARNING: An upgrade from Fedora $VERSION_ID to Fedora $VERSION_NEXT is commencing! Your computer will reboot in 60 seconds."

	sleep 60

	dnf system-upgrade reboot -y
}

check